# docu: https://luna.gitlab.io/hypercorn/how_to_guides/configuring.html#configuration-options

[server]
workers = 2                # Nombre de processus travailleurs
keep_alive = 10            # Temps d'attente avant de fermer une connexion inactive

[logging]
loglevel = "info"           # Niveau de journalisation
accesslog = "logs/public.log"    # Fichier pour les journaux d'accès
errorlog = "logs/error.log"      # Fichier pour les erreurs